site_name: "Wisdom Water"
site_url: https://wisdomwater.github.io/
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - toc.integrate

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
      baselevel: 2
  - pymdownx.snippets:
      base_path:
        - .   # allow includes from repo root (so "external/..." works)

nav:
  - Home: index.md
  - Books:
    - "Aurora": the-first-light/index.md
    # KDP_SELECT - "Pistis Sophia": pistis-sophia/index.md
    - "Phaedo": phaedo/index.md
    - "The God Who Sees": the-god-who-sees/index.md
    - "The Greater Mercy": the-greater-mercy/index.md
    - "The Journey Home": the-journey-home/index.md
    - "The Tibetan Book of the Dead": bardo-thodol/index.md
    - "The Way of the Pilgrim": the-way-of-the-pilgrim/index.md
